version: '2.1'

services:
  scotty-server:
    image: scotty-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    ## set your startup file here
    command: nodemon
  scotty-client:
    image: scotty-client
    build: .
    command: yarn start

